// 실제 데이터 연결(Supabase) 전까지 화면 확인용으로 쓰는 예시 데이터입니다.
// recipes 테이블 구조(id, slug, name, tags 등)에 맞춰 임시로 만든 목데이터이며,
// 실제 레시피 출처/내용이 아닙니다.
//
// 언어 토글(한국어/영어) 지원을 위해 nameEn / celebrityNameEn / ingredients[].nameEn /
// instructionsEn / sourceNameEn 필드를 함께 둡니다. 실제 서비스에서는 recipes 테이블에
// 같은 이름의 컬럼(또는 translations 서브테이블)으로 옮기면 됩니다.

export type FlavorTag = "매콤" | "고소" | "짭짤";
export type CountryTag = "한식" | "중식" | "양식" | "일식" | "멕시칸";
// 국가별 분류와는 별개의 축입니다. 브랜드·상황 기준으로 묶고 싶은 소스(하이디라오
// 소스바 조합, 훠궈 등 핫팟류 찍먹 소스 전반)를 위한 태그로, 국가 분류를 계속 5개로
// 고정해두고 싶어서 별도로 분리했습니다. 필요해지면 이 목록에만 추가하면 됩니다.
export type ThemeTag = "하이디라오";

export type IngredientUnit = "큰술" | "작은술" | "ml" | "g";

export interface Ingredient {
  name: string;
  nameEn: string;
  amount: number;
  unit: IngredientUnit;
  densityGPerMl?: number; // g 단위 재료의 US 환산용 밀도(g/ml). 없으면 물 기준(1) 근사치 사용
}

export interface MockRecipe {
  id: string;
  slug: string;
  name: string;
  nameEn: string;
  flavor: FlavorTag;
  country: CountryTag;
  theme?: ThemeTag; // 국가 분류와 별개인 브랜드·상황 태그 (예: 하이디라오 소스바류)
  celebrityName?: string; // 예: "건희" -> 제목에 "건희가 소개한 ~"로 표시 + #건희 해시태그(검색용) 병행
  celebrityNameEn?: string; // 영어 화면용 로마자 표기 (예: "Geonhui")
  spiceLevel: number; // 0(순함) ~ 3(제일 매움). 벤치마킹(saucepick.com) 후 추가
  photoUrl?: string; // 완성 사진(공개용). 아직 실제 업로드 기능 전이라 목데이터에는 없음 -> 빈 값이면 사진 자리에 아이콘만 표시
  likeCount: number;
  liked: boolean; // 로그인 사용자가 좋아요 눌렀는지 (지금은 목데이터라 고정값)
  createdAt: string; // ISO date
  saved: boolean; // 로그인 사용자의 즐겨찾기 여부 (지금은 목데이터라 고정값)
  ingredients: Ingredient[];
  instructions: string; // 조리 순서(간단 설명)
  instructionsEn: string;
  sourceUrl: string;
  sourceName: string;
  sourceNameEn: string;
}

export const mockRecipes: MockRecipe[] = [
  {
    id: "1",
    slug: "mala-hotpot-sauce",
    name: "마라 훠궈 소스",
    nameEn: "Mala Hotpot Sauce",
    flavor: "매콤",
    country: "중식",
    theme: "하이디라오",
    spiceLevel: 1,
    celebrityName: "건희",
    celebrityNameEn: "Geonhui",
    likeCount: 128,
    createdAt: "2026-07-20",
    saved: true,
    liked: false,
    ingredients: [
      { name: "땅콩소스", nameEn: "Peanut sauce", amount: 1, unit: "큰술" },
      { name: "칠리소스", nameEn: "Chili sauce", amount: 2, unit: "큰술" },
      { name: "다진마늘", nameEn: "Minced garlic", amount: 0.5, unit: "큰술" },
      { name: "참깨", nameEn: "Sesame seeds", amount: 1, unit: "작은술" },
      { name: "고추기름", nameEn: "Chili oil", amount: 0.5, unit: "큰술" },
      { name: "설탕", nameEn: "Sugar", amount: 15, unit: "g", densityGPerMl: 0.85 },
    ],
    instructions: "모든 재료를 볼에 넣고 골고루 섞어주세요. 매운 정도는 칠리소스 양으로 조절합니다.",
    instructionsEn:
      "Combine all ingredients in a bowl and mix well. Adjust the spice level by changing the amount of chili sauce.",
    sourceUrl: "https://x.com/example_source1",
    sourceName: "X(트위터) 공개 게시물",
    sourceNameEn: "Public post on X (Twitter)",
  },
  {
    id: "2",
    slug: "ssamjang-style-sauce",
    name: "쌈장 스타일 소스",
    nameEn: "Ssamjang-Style Sauce",
    flavor: "짭짤",
    country: "한식",
    spiceLevel: 1,
    likeCount: 96,
    createdAt: "2026-07-18",
    saved: true,
    liked: false,
    ingredients: [
      { name: "쌈장", nameEn: "Ssamjang (soybean paste)", amount: 2, unit: "큰술" },
      { name: "참기름", nameEn: "Sesame oil", amount: 1, unit: "큰술" },
      { name: "다진마늘", nameEn: "Minced garlic", amount: 0.5, unit: "큰술" },
      { name: "참깨", nameEn: "Sesame seeds", amount: 1, unit: "작은술" },
      { name: "설탕", nameEn: "Sugar", amount: 5, unit: "g", densityGPerMl: 0.85 },
    ],
    instructions: "재료를 골고루 섞고 냉장 보관 후 찍어 드세요.",
    instructionsEn: "Mix the ingredients well, refrigerate, and use as a dip.",
    sourceUrl: "https://x.com/example_source2",
    sourceName: "X(트위터) 공개 게시물",
    sourceNameEn: "Public post on X (Twitter)",
  },
  {
    id: "3",
    slug: "peanut-sesame-sauce",
    name: "땅콩깨 소스",
    nameEn: "Peanut Sesame Sauce",
    flavor: "고소",
    country: "중식",
    spiceLevel: 1,
    celebrityName: "이영지",
    celebrityNameEn: "Lee Young-ji",
    likeCount: 210,
    createdAt: "2026-07-15",
    saved: false,
    liked: false,
    ingredients: [
      { name: "땅콩소스", nameEn: "Peanut sauce", amount: 2, unit: "큰술" },
      { name: "참깨", nameEn: "Sesame seeds", amount: 1, unit: "큰술" },
      { name: "간장", nameEn: "Soy sauce", amount: 1, unit: "큰술" },
      { name: "설탕", nameEn: "Sugar", amount: 10, unit: "g", densityGPerMl: 0.85 },
      { name: "식초", nameEn: "Vinegar", amount: 1, unit: "작은술" },
    ],
    instructions: "땅콩소스와 간장을 먼저 섞은 뒤 나머지 재료를 넣고 잘 저어줍니다.",
    instructionsEn:
      "Mix the peanut sauce and soy sauce first, then add the remaining ingredients and stir well.",
    sourceUrl: "https://x.com/example_source3",
    sourceName: "X(트위터) 공개 게시물",
    sourceNameEn: "Public post on X (Twitter)",
  },
  {
    id: "4",
    slug: "yuzu-ponzu-sauce",
    name: "유자폰즈 소스",
    nameEn: "Yuzu Ponzu Sauce",
    flavor: "짭짤",
    country: "일식",
    spiceLevel: 0,
    likeCount: 74,
    createdAt: "2026-07-22",
    saved: false,
    liked: false,
    ingredients: [
      { name: "유자청", nameEn: "Yuzu syrup", amount: 1, unit: "큰술" },
      { name: "간장", nameEn: "Soy sauce", amount: 2, unit: "큰술" },
      { name: "식초", nameEn: "Vinegar", amount: 1, unit: "큰술" },
      { name: "다시마육수", nameEn: "Kelp broth", amount: 30, unit: "ml" },
    ],
    instructions: "모든 재료를 섞어 냉장고에 10분 정도 두었다가 사용하면 더 어울립니다.",
    instructionsEn:
      "Mix all ingredients and let sit in the fridge for about 10 minutes for the best flavor.",
    sourceUrl: "https://x.com/example_source4",
    sourceName: "X(트위터) 공개 게시물",
    sourceNameEn: "Public post on X (Twitter)",
  },
  {
    id: "5",
    slug: "gochujang-mayo-sauce",
    name: "고추장 마요 소스",
    nameEn: "Gochujang Mayo Sauce",
    flavor: "매콤",
    country: "한식",
    spiceLevel: 2,
    celebrityName: "김풍",
    celebrityNameEn: "Kim Poong",
    likeCount: 156,
    createdAt: "2026-07-10",
    saved: true,
    liked: false,
    ingredients: [
      { name: "고추장", nameEn: "Gochujang", amount: 1, unit: "큰술" },
      { name: "마요네즈", nameEn: "Mayonnaise", amount: 2, unit: "큰술" },
      { name: "설탕", nameEn: "Sugar", amount: 10, unit: "g", densityGPerMl: 0.85 },
      { name: "식초", nameEn: "Vinegar", amount: 1, unit: "작은술" },
    ],
    instructions: "고추장과 마요네즈를 먼저 섞은 뒤 설탕과 식초로 간을 맞춥니다.",
    instructionsEn:
      "Mix the gochujang and mayonnaise first, then season with sugar and vinegar to taste.",
    sourceUrl: "https://x.com/example_source5",
    sourceName: "X(트위터) 공개 게시물",
    sourceNameEn: "Public post on X (Twitter)",
  },
  {
    id: "6",
    slug: "salsa-verde-sauce",
    name: "살사 베르데 소스",
    nameEn: "Salsa Verde Sauce",
    flavor: "매콤",
    country: "멕시칸",
    spiceLevel: 2,
    likeCount: 41,
    createdAt: "2026-07-05",
    saved: false,
    liked: false,
    ingredients: [
      { name: "다진 할라피뇨", nameEn: "Minced jalapeño", amount: 1, unit: "큰술" },
      { name: "다진 고수", nameEn: "Minced cilantro", amount: 1, unit: "큰술" },
      { name: "라임즙", nameEn: "Lime juice", amount: 1, unit: "큰술" },
      { name: "올리브유", nameEn: "Olive oil", amount: 2, unit: "큰술" },
      { name: "소금", nameEn: "Salt", amount: 3, unit: "g", densityGPerMl: 1.2 },
    ],
    instructions: "모든 재료를 잘게 다져 섞고 라임즙과 소금으로 간을 맞춥니다.",
    instructionsEn: "Finely chop and mix all ingredients, then season with lime juice and salt.",
    sourceUrl: "https://x.com/example_source6",
    sourceName: "X(트위터) 공개 게시물",
    sourceNameEn: "Public post on X (Twitter)",
  },
  {
    id: "7",
    slug: "garlic-butter-sauce",
    name: "갈릭버터 소스",
    nameEn: "Garlic Butter Sauce",
    flavor: "고소",
    country: "양식",
    spiceLevel: 0,
    celebrityName: "샤오쥔",
    celebrityNameEn: "Xiaojun",
    likeCount: 187,
    createdAt: "2026-07-23",
    saved: true,
    liked: false,
    ingredients: [
      { name: "버터", nameEn: "Butter", amount: 20, unit: "g", densityGPerMl: 0.9 },
      { name: "다진마늘", nameEn: "Minced garlic", amount: 1, unit: "큰술" },
      { name: "파슬리", nameEn: "Parsley", amount: 1, unit: "작은술" },
      { name: "소금", nameEn: "Salt", amount: 2, unit: "g", densityGPerMl: 1.2 },
    ],
    instructions: "버터를 약불에 녹인 뒤 다진마늘을 넣고 향이 올라오면 소금과 파슬리로 마무리합니다.",
    instructionsEn:
      "Melt the butter over low heat, add the minced garlic, and once fragrant, finish with salt and parsley.",
    sourceUrl: "https://x.com/example_source7",
    sourceName: "X(트위터) 공개 게시물",
    sourceNameEn: "Public post on X (Twitter)",
  },
  {
    id: "8",
    slug: "sesame-soy-sauce",
    name: "참깨간장 소스",
    nameEn: "Sesame Soy Sauce",
    flavor: "짭짤",
    country: "일식",
    spiceLevel: 1,
    likeCount: 63,
    createdAt: "2026-07-12",
    saved: false,
    liked: false,
    ingredients: [
      { name: "간장", nameEn: "Soy sauce", amount: 2, unit: "큰술" },
      { name: "참기름", nameEn: "Sesame oil", amount: 1, unit: "큰술" },
      { name: "참깨", nameEn: "Sesame seeds", amount: 1, unit: "큰술" },
      { name: "식초", nameEn: "Vinegar", amount: 1, unit: "작은술" },
      { name: "설탕", nameEn: "Sugar", amount: 5, unit: "g", densityGPerMl: 0.85 },
    ],
    instructions: "모든 재료를 섞어 냉장 보관하고, 찍먹 소스로 사용합니다.",
    instructionsEn: "Mix all ingredients, refrigerate, and use as a dipping sauce.",
    sourceUrl: "https://x.com/example_source8",
    sourceName: "X(트위터) 공개 게시물",
    sourceNameEn: "Public post on X (Twitter)",
  },
  // ↓ 여기서부터는 실제 출처가 확인된 레시피입니다 (2026-08-16 배치, 사용자 구글 드라이브
  // "레시피 저장" 문서 + 언론/유튜브/나무위키 등 공개 출처로 교차 검증).
  {
    id: "9",
    slug: "peanut-garlic-hotpot-sauce",
    name: "땅콩마늘 훠궈 소스",
    nameEn: "Peanut Garlic Hotpot Sauce",
    flavor: "고소",
    country: "중식",
    theme: "하이디라오",
    spiceLevel: 1,
    celebrityName: "마크",
    celebrityNameEn: "Mark (NCT)",
    likeCount: 142,
    createdAt: "2026-08-10",
    saved: false,
    liked: false,
    ingredients: [
      { name: "땅콩소스", nameEn: "Peanut sauce", amount: 2, unit: "큰술" },
      { name: "다진마늘", nameEn: "Minced garlic", amount: 1.5, unit: "큰술" },
      { name: "다진양파", nameEn: "Chopped onion", amount: 1.5, unit: "큰술" },
      { name: "굴소스", nameEn: "Oyster sauce", amount: 1, unit: "큰술" },
      { name: "태국고추", nameEn: "Thai chili", amount: 1, unit: "큰술" },
      { name: "간장", nameEn: "Soy sauce", amount: 2, unit: "큰술" },
      { name: "다진고기", nameEn: "Minced meat", amount: 0.5, unit: "큰술" },
      { name: "땅콩가루", nameEn: "Peanut powder", amount: 0.5, unit: "큰술" },
    ],
    instructions:
      "땅콩소스·간장·굴소스를 먼저 섞고 다진마늘·양파·태국고추를 넣어 골고루 섞어주세요. 다진고기를 살짝 볶아 넣으면 더 고소해집니다.",
    instructionsEn:
      "Mix the peanut sauce, soy sauce, and oyster sauce first, then add the minced garlic, onion, and Thai chili. Lightly sautéing the minced meat before adding makes it even nuttier.",
    sourceUrl: "https://www.esquirekorea.co.kr/article/1880880",
    sourceName: "에스콰이어 코리아 - 2025년 버전 아이돌의 하이디라오 소스 레시피",
    sourceNameEn: "Esquire Korea - 2025 Idol Haidilao Sauce Recipes",
  },
  {
    id: "10",
    slug: "mala-seasoning-hotpot-sauce",
    name: "마라시즈닝 훠궈 소스",
    nameEn: "Mala Seasoning Hotpot Sauce",
    flavor: "매콤",
    country: "중식",
    theme: "하이디라오",
    spiceLevel: 2,
    celebrityName: "필릭스",
    celebrityNameEn: "Felix (Stray Kids)",
    likeCount: 118,
    createdAt: "2026-08-10",
    saved: false,
    liked: false,
    ingredients: [
      { name: "땅콩소스", nameEn: "Peanut sauce", amount: 1, unit: "큰술" },
      { name: "다진마늘", nameEn: "Minced garlic", amount: 1, unit: "큰술" },
      { name: "다진파", nameEn: "Chopped green onion", amount: 0.3, unit: "큰술" },
      { name: "마라시즈닝", nameEn: "Mala seasoning", amount: 1, unit: "큰술" },
      { name: "다진양파", nameEn: "Chopped onion", amount: 1, unit: "큰술" },
      { name: "청유훼궈소스", nameEn: "Green hotpot sauce", amount: 1, unit: "큰술" },
    ],
    instructions:
      "모든 재료를 볼에 넣고 골고루 섞어주세요. 마라시즈닝 양으로 얼얼한 정도를 조절할 수 있습니다.",
    instructionsEn:
      "Combine all ingredients in a bowl and mix well. Adjust the numbing spice level with the amount of mala seasoning.",
    sourceUrl: "https://www.esquirekorea.co.kr/article/1880880",
    sourceName: "에스콰이어 코리아 - 2025년 버전 아이돌의 하이디라오 소스 레시피",
    sourceNameEn: "Esquire Korea - 2025 Idol Haidilao Sauce Recipes",
  },
  {
    id: "11",
    slug: "mushroom-peanut-hotpot-sauce",
    name: "버섯땅콩 훠궈 소스",
    nameEn: "Mushroom Peanut Hotpot Sauce",
    flavor: "고소",
    country: "중식",
    theme: "하이디라오",
    spiceLevel: 1,
    celebrityName: "아이엔",
    celebrityNameEn: "Ain",
    likeCount: 64,
    createdAt: "2026-08-10",
    saved: false,
    liked: false,
    ingredients: [
      { name: "땅콩소스", nameEn: "Peanut sauce", amount: 1, unit: "큰술" },
      { name: "버섯소스", nameEn: "Mushroom sauce", amount: 1, unit: "큰술" },
      { name: "다진마늘", nameEn: "Minced garlic", amount: 1, unit: "큰술" },
      { name: "다진파", nameEn: "Chopped green onion", amount: 0.3, unit: "큰술" },
      { name: "오향우육", nameEn: "Five-spice beef sauce", amount: 1, unit: "큰술" },
      { name: "매운소고기소스", nameEn: "Spicy beef sauce", amount: 1, unit: "큰술" },
    ],
    instructions: "모든 재료를 볼에 넣고 골고루 섞어주세요.",
    instructionsEn: "Combine all ingredients in a bowl and mix well.",
    sourceUrl: "https://www.esquirekorea.co.kr/article/1880880",
    sourceName: "에스콰이어 코리아 - 2025년 버전 아이돌의 하이디라오 소스 레시피",
    sourceNameEn: "Esquire Korea - 2025 Idol Haidilao Sauce Recipes",
  },
  {
    id: "12",
    slug: "peanut-vinegar-hotpot-sauce",
    name: "땅콩식초 훠궈 소스",
    nameEn: "Peanut Vinegar Hotpot Sauce",
    flavor: "짭짤",
    country: "중식",
    theme: "하이디라오",
    spiceLevel: 0,
    celebrityName: "우기",
    celebrityNameEn: "Yuqi ((G)I-DLE)",
    likeCount: 133,
    createdAt: "2026-08-10",
    saved: true,
    liked: false,
    ingredients: [
      { name: "땅콩소스", nameEn: "Peanut sauce", amount: 1.5, unit: "큰술" },
      { name: "다진파", nameEn: "Chopped green onion", amount: 1, unit: "큰술" },
      { name: "고수", nameEn: "Cilantro", amount: 1, unit: "큰술" },
      { name: "다진마늘", nameEn: "Minced garlic", amount: 1, unit: "큰술" },
      { name: "중국식초", nameEn: "Chinese black vinegar", amount: 2, unit: "큰술" },
      { name: "땅콩가루", nameEn: "Peanut powder", amount: 1, unit: "큰술" },
    ],
    instructions:
      "중국식초를 넉넉히 넣어야 느끼함이 잡히고 개운해집니다. 나머지 재료를 넣고 골고루 섞어주세요.",
    instructionsEn:
      "A generous amount of Chinese black vinegar cuts the richness and makes it refreshing. Add the rest of the ingredients and mix well.",
    sourceUrl: "https://www.esquirekorea.co.kr/article/1880880",
    sourceName: "에스콰이어 코리아 - 2025년 버전 아이돌의 하이디라오 소스 레시피",
    sourceNameEn: "Esquire Korea - 2025 Idol Haidilao Sauce Recipes",
  },
  {
    id: "13",
    slug: "peanut-chili-hotpot-sauce-2025",
    name: "땅콩칠리 훠궈 소스",
    nameEn: "Peanut Chili Hotpot Sauce",
    flavor: "매콤",
    country: "중식",
    theme: "하이디라오",
    spiceLevel: 1,
    celebrityName: "건희",
    celebrityNameEn: "Geonhui (ONEUS)",
    likeCount: 231,
    createdAt: "2026-08-10",
    saved: true,
    liked: false,
    ingredients: [
      { name: "땅콩소스", nameEn: "Peanut sauce", amount: 1, unit: "큰술" },
      { name: "칠리소스", nameEn: "Chili sauce", amount: 1, unit: "큰술" },
      { name: "다진파", nameEn: "Chopped green onion", amount: 1, unit: "큰술" },
      { name: "다진마늘", nameEn: "Minced garlic", amount: 1, unit: "큰술" },
      { name: "고추기름", nameEn: "Chili oil", amount: 0.3, unit: "큰술" },
      { name: "굴소스", nameEn: "Oyster sauce", amount: 0.3, unit: "큰술" },
      { name: "태국고추", nameEn: "Thai chili", amount: 0.3, unit: "큰술" },
      { name: "참깨가루", nameEn: "Sesame powder", amount: 0.3, unit: "큰술" },
    ],
    instructions:
      "땅콩소스·칠리소스·굴소스를 먼저 섞고 나머지 재료를 넣어 골고루 섞어주세요. 2025년 개정판은 설탕을 빼서 더 깔끔한 단짠 밸런스가 특징입니다.",
    instructionsEn:
      "Mix the peanut sauce, chili sauce, and oyster sauce first, then add the rest. The 2025 update drops the sugar for a cleaner sweet-savory balance.",
    sourceUrl: "https://www.esquirekorea.co.kr/article/1880880",
    sourceName: "에스콰이어 코리아 - 2025년 버전 아이돌의 하이디라오 소스 레시피",
    sourceNameEn: "Esquire Korea - 2025 Idol Haidilao Sauce Recipes",
  },
  {
    id: "14",
    slug: "sesame-beef-hotpot-sauce",
    name: "참깨소고기 훠궈 소스",
    nameEn: "Sesame Beef Hotpot Sauce",
    flavor: "고소",
    country: "중식",
    theme: "하이디라오",
    spiceLevel: 1,
    celebrityName: "성찬",
    celebrityNameEn: "Seongchan (RIIZE)",
    likeCount: 87,
    createdAt: "2026-08-10",
    saved: false,
    liked: false,
    ingredients: [
      { name: "참깨소스", nameEn: "Sesame sauce", amount: 2, unit: "큰술" },
      { name: "칠리소스", nameEn: "Chili sauce", amount: 1, unit: "큰술" },
      { name: "다진고기", nameEn: "Minced meat", amount: 2, unit: "큰술" },
      { name: "다진마늘", nameEn: "Minced garlic", amount: 1, unit: "큰술" },
      { name: "쪽파", nameEn: "Thin green onion", amount: 1.5, unit: "큰술" },
      { name: "땅콩가루", nameEn: "Peanut powder", amount: 1, unit: "큰술" },
    ],
    instructions: "모든 재료를 볼에 넣고 골고루 섞어주세요.",
    instructionsEn: "Combine all ingredients in a bowl and mix well.",
    sourceUrl: "https://www.esquirekorea.co.kr/article/1880880",
    sourceName: "에스콰이어 코리아 - 2025년 버전 아이돌의 하이디라오 소스 레시피",
    sourceNameEn: "Esquire Korea - 2025 Idol Haidilao Sauce Recipes",
  },
  {
    id: "15",
    slug: "sesame-oil-garlic-hotpot-sauce",
    name: "참기름마늘 훠궈 소스",
    nameEn: "Sesame Oil Garlic Hotpot Sauce",
    flavor: "고소",
    country: "중식",
    theme: "하이디라오",
    spiceLevel: 0,
    celebrityName: "소희",
    celebrityNameEn: "Sohee (RIIZE)",
    likeCount: 79,
    createdAt: "2026-08-10",
    saved: false,
    liked: false,
    ingredients: [
      { name: "참기름", nameEn: "Sesame oil", amount: 3, unit: "큰술" },
      { name: "다진마늘", nameEn: "Minced garlic", amount: 1, unit: "큰술" },
      { name: "볶음소고기장", nameEn: "Sautéed beef paste", amount: 0.5, unit: "큰술" },
      { name: "칠리소스", nameEn: "Chili sauce", amount: 0.5, unit: "큰술" },
      { name: "굴소스", nameEn: "Oyster sauce", amount: 1, unit: "큰술" },
    ],
    instructions: "모든 재료를 볼에 넣고 골고루 섞어주세요.",
    instructionsEn: "Combine all ingredients in a bowl and mix well.",
    sourceUrl: "https://www.esquirekorea.co.kr/article/1880880",
    sourceName: "에스콰이어 코리아 - 2025년 버전 아이돌의 하이디라오 소스 레시피",
    sourceNameEn: "Esquire Korea - 2025 Idol Haidilao Sauce Recipes",
  },
  {
    id: "16",
    slug: "cilantro-soy-hotpot-sauce",
    name: "고수간장 훠궈 소스",
    nameEn: "Cilantro Soy Hotpot Sauce",
    flavor: "짭짤",
    country: "중식",
    theme: "하이디라오",
    spiceLevel: 1,
    celebrityName: "지수",
    celebrityNameEn: "Jisoo (BLACKPINK)",
    likeCount: 302,
    createdAt: "2026-08-12",
    saved: true,
    liked: false,
    ingredients: [
      { name: "고수", nameEn: "Cilantro", amount: 3, unit: "큰술" },
      { name: "다진파", nameEn: "Chopped green onion", amount: 0.5, unit: "큰술" },
      { name: "고추냉이", nameEn: "Wasabi", amount: 0.3, unit: "작은술" },
      { name: "다진마늘", nameEn: "Minced garlic", amount: 0.5, unit: "큰술" },
      { name: "다진고추", nameEn: "Minced chili", amount: 0.5, unit: "큰술" },
      { name: "간장", nameEn: "Soy sauce", amount: 3, unit: "큰술" },
      { name: "설탕", nameEn: "Sugar", amount: 3, unit: "g", densityGPerMl: 0.85 },
      { name: "중국식초", nameEn: "Chinese black vinegar", amount: 1, unit: "큰술" },
      { name: "참기름", nameEn: "Sesame oil", amount: 1, unit: "큰술" },
    ],
    instructions:
      "고수를 듬뿍 담고 다진 파와 고추냉이를 조금 더합니다. 마늘·고추는 취향껏 넣고, 땅콩류 베이스보다 간장을 넉넉히 넣는 게 포인트예요. 설탕 약간과 중국식초 1큰술을 넣고, 마지막에 참기름 1큰술로 마무리합니다.",
    instructionsEn:
      "Pile on the cilantro, then add a touch of chopped green onion and wasabi. Add garlic and chili to taste — soy sauce, not a peanut base, is the key here. Add a little sugar and a tablespoon of Chinese black vinegar, then finish with a tablespoon of sesame oil.",
    sourceUrl: "https://www.esquirekorea.co.kr/article/1898094",
    sourceName: "에스콰이어 코리아 - [단독] 블랙핑크 지수가 직접 알려주는 훠궈집 본전 뽑기",
    sourceNameEn: "Esquire Korea - Exclusive: BLACKPINK Jisoo's Hotpot Guide",
  },
  {
    id: "17",
    slug: "sesame-peanut-hotpot-sauce-official",
    name: "참깨땅콩 훠궈 소스 (하이디라오 공식)",
    nameEn: "Sesame Peanut Hotpot Sauce (Haidilao Official)",
    flavor: "고소",
    country: "중식",
    theme: "하이디라오",
    spiceLevel: 0,
    likeCount: 55,
    createdAt: "2026-08-13",
    saved: false,
    liked: false,
    ingredients: [
      { name: "참깨소스", nameEn: "Sesame sauce", amount: 3, unit: "큰술" },
      { name: "다진파", nameEn: "Chopped green onion", amount: 0.3, unit: "큰술" },
      { name: "다진마늘", nameEn: "Minced garlic", amount: 0.3, unit: "큰술" },
      { name: "땅콩가루", nameEn: "Peanut powder", amount: 0.3, unit: "큰술" },
    ],
    instructions:
      "재료를 골고루 섞어주세요. 토마토탕·삼선탕·버섯탕·해산물과 잘 어울리고, 기호에 따라 태국고추를 더해도 좋습니다.",
    instructionsEn:
      "Mix well. Pairs nicely with tomato, sanxian, mushroom, and seafood hotpot broths — add Thai chili if you like it spicier.",
    sourceUrl: "https://www.facebook.com/HaidilaoKorea/",
    sourceName: "하이디라오 코리아 공식 (매장 터치스크린 메뉴 소스 구성)",
    sourceNameEn: "Haidilao Korea Official (in-store touchscreen menu sauce guide)",
  },
  {
    id: "18",
    slug: "hotpot-chili-sauce-official",
    name: "훠궈 칠리 소스 (하이디라오 공식)",
    nameEn: "Hotpot Chili Sauce (Haidilao Official)",
    flavor: "매콤",
    country: "중식",
    theme: "하이디라오",
    spiceLevel: 1,
    likeCount: 48,
    createdAt: "2026-08-13",
    saved: false,
    liked: false,
    ingredients: [
      { name: "스위트칠리소스", nameEn: "Sweet chili sauce", amount: 1, unit: "큰술" },
      { name: "청유훼궈소스", nameEn: "Green hotpot sauce", amount: 1, unit: "큰술" },
      { name: "고춧가루", nameEn: "Red pepper powder", amount: 0.5, unit: "큰술" },
      { name: "다진마늘", nameEn: "Minced garlic", amount: 0.3, unit: "큰술" },
      { name: "땅콩가루", nameEn: "Peanut powder", amount: 0.3, unit: "큰술" },
      { name: "굴소스", nameEn: "Oyster sauce", amount: 0.3, unit: "큰술" },
    ],
    instructions: "재료를 골고루 섞어주세요. 모든 탕 종류에 두루 잘 어울리는 조합입니다.",
    instructionsEn: "Mix well — this combination pairs with pretty much any broth.",
    sourceUrl: "https://www.facebook.com/HaidilaoKorea/",
    sourceName: "하이디라오 코리아 공식 (매장 터치스크린 메뉴 소스 구성)",
    sourceNameEn: "Haidilao Korea Official (in-store touchscreen menu sauce guide)",
  },
  {
    id: "19",
    slug: "meatball-soy-sauce-official",
    name: "완자 간장 소스 (하이디라오 공식)",
    nameEn: "Meatball Soy Sauce (Haidilao Official)",
    flavor: "짭짤",
    country: "중식",
    theme: "하이디라오",
    spiceLevel: 0,
    likeCount: 39,
    createdAt: "2026-08-13",
    saved: false,
    liked: false,
    ingredients: [
      { name: "간장소스", nameEn: "Soy sauce base", amount: 3, unit: "큰술" },
      { name: "다진마늘", nameEn: "Minced garlic", amount: 0.3, unit: "큰술" },
      { name: "다진파", nameEn: "Chopped green onion", amount: 0.3, unit: "큰술" },
      { name: "태국고추", nameEn: "Thai chili", amount: 0.3, unit: "큰술" },
      { name: "굴소스", nameEn: "Oyster sauce", amount: 0.3, unit: "큰술" },
    ],
    instructions:
      "재료를 골고루 섞어주세요. 삼선탕·버섯탕·삼계탕·해산물과 잘 어울리고, 기호에 따라 고수를 더해도 좋습니다.",
    instructionsEn:
      "Mix well. Pairs with sanxian, mushroom, samgyetang, and seafood broths — add cilantro if you like.",
    sourceUrl: "https://www.facebook.com/HaidilaoKorea/",
    sourceName: "하이디라오 코리아 공식 (매장 터치스크린 메뉴 소스 구성)",
    sourceNameEn: "Haidilao Korea Official (in-store touchscreen menu sauce guide)",
  },
  {
    id: "20",
    slug: "sesame-oil-garlic-sauce-official",
    name: "참기름 마늘 소스 (하이디라오 공식)",
    nameEn: "Sesame Oil Garlic Sauce (Haidilao Official)",
    flavor: "고소",
    country: "중식",
    theme: "하이디라오",
    spiceLevel: 1,
    likeCount: 61,
    createdAt: "2026-08-13",
    saved: false,
    liked: false,
    ingredients: [
      { name: "참기름", nameEn: "Sesame oil", amount: 3, unit: "큰술" },
      { name: "다진마늘", nameEn: "Minced garlic", amount: 1, unit: "큰술" },
      { name: "굴소스", nameEn: "Oyster sauce", amount: 1, unit: "큰술" },
      { name: "고춧가루", nameEn: "Red pepper powder", amount: 0.3, unit: "큰술" },
    ],
    instructions: "재료를 골고루 섞어주세요. 마라탕과 특히 잘 어울립니다.",
    instructionsEn: "Mix well — this one pairs especially well with mala broth.",
    sourceUrl: "https://www.facebook.com/HaidilaoKorea/",
    sourceName: "하이디라오 코리아 공식 (매장 터치스크린 메뉴 소스 구성)",
    sourceNameEn: "Haidilao Korea Official (in-store touchscreen menu sauce guide)",
  },
  {
    id: "21",
    slug: "mushroom-beef-hotpot-sauce-official",
    name: "버섯소고기 훠궈 소스 (하이디라오 공식)",
    nameEn: "Mushroom Beef Hotpot Sauce (Haidilao Official)",
    flavor: "짭짤",
    country: "중식",
    theme: "하이디라오",
    spiceLevel: 1,
    likeCount: 33,
    createdAt: "2026-08-13",
    saved: false,
    liked: false,
    ingredients: [
      { name: "버섯소스", nameEn: "Mushroom sauce", amount: 0.5, unit: "큰술" },
      { name: "매운소고기소스", nameEn: "Spicy beef sauce", amount: 0.5, unit: "큰술" },
      { name: "참깨소스", nameEn: "Sesame sauce", amount: 1, unit: "큰술" },
      { name: "다진파", nameEn: "Chopped green onion", amount: 0.3, unit: "큰술" },
    ],
    instructions: "재료를 골고루 섞어주세요. 마라탕·버섯탕·토마토탕과 잘 어울립니다.",
    instructionsEn: "Mix well. Pairs with mala, mushroom, and tomato broths.",
    sourceUrl: "https://www.facebook.com/HaidilaoKorea/",
    sourceName: "하이디라오 코리아 공식 (매장 터치스크린 메뉴 소스 구성)",
    sourceNameEn: "Haidilao Korea Official (in-store touchscreen menu sauce guide)",
  },
  {
    id: "22",
    slug: "sacha-seafood-sauce-official",
    name: "사차장 해산물 소스 (하이디라오 공식)",
    nameEn: "Sha Cha Seafood Sauce (Haidilao Official)",
    flavor: "짭짤",
    country: "중식",
    theme: "하이디라오",
    spiceLevel: 0,
    likeCount: 27,
    createdAt: "2026-08-13",
    saved: false,
    liked: false,
    ingredients: [
      { name: "사차장", nameEn: "Sha cha sauce", amount: 1, unit: "큰술" },
      { name: "간장소스", nameEn: "Soy sauce base", amount: 1, unit: "큰술" },
      { name: "참깨소스", nameEn: "Sesame sauce", amount: 0.5, unit: "큰술" },
      { name: "고추기름", nameEn: "Chili oil", amount: 0.3, unit: "큰술" },
      { name: "다진파", nameEn: "Chopped green onion", amount: 0.3, unit: "큰술" },
    ],
    instructions:
      "재료를 골고루 섞어주세요. 삼선탕·버섯탕·토마토탕·해산물과 잘 어울리고, 기호에 따라 고수를 더해도 좋습니다.",
    instructionsEn: "Mix well. Pairs with sanxian, mushroom, tomato, and seafood broths.",
    sourceUrl: "https://www.facebook.com/HaidilaoKorea/",
    sourceName: "하이디라오 코리아 공식 (매장 터치스크린 메뉴 소스 구성)",
    sourceNameEn: "Haidilao Korea Official (in-store touchscreen menu sauce guide)",
  },
  {
    id: "23",
    slug: "staff-secret-hotpot-sauce-official",
    name: "직원 비법 훠궈 소스 (하이디라오 공식)",
    nameEn: "Staff Secret Hotpot Sauce (Haidilao Official)",
    flavor: "매콤",
    country: "중식",
    theme: "하이디라오",
    spiceLevel: 2,
    likeCount: 71,
    createdAt: "2026-08-13",
    saved: false,
    liked: false,
    ingredients: [
      { name: "참기름", nameEn: "Sesame oil", amount: 2, unit: "큰술" },
      { name: "고추기름", nameEn: "Chili oil", amount: 0.7, unit: "큰술" },
      { name: "굴소스", nameEn: "Oyster sauce", amount: 0.7, unit: "큰술" },
      { name: "태국고추", nameEn: "Thai chili", amount: 0.5, unit: "큰술" },
      { name: "고춧가루", nameEn: "Red pepper powder", amount: 0.5, unit: "큰술" },
      { name: "땅콩가루", nameEn: "Peanut powder", amount: 0.5, unit: "큰술" },
      { name: "설탕", nameEn: "Sugar", amount: 5, unit: "g", densityGPerMl: 0.85 },
      { name: "다진파", nameEn: "Chopped green onion", amount: 0.3, unit: "큰술" },
      { name: "고수", nameEn: "Cilantro", amount: 0.3, unit: "큰술" },
      { name: "다진마늘", nameEn: "Minced garlic", amount: 0.3, unit: "큰술" },
      { name: "산초기름", nameEn: "Sichuan pepper oil", amount: 0.2, unit: "큰술" },
    ],
    instructions:
      "매장 직원이 공유한 비법 배합으로, 재료를 골고루 섞어주세요. 고추기름과 산초기름 비율로 얼얼한 정도를 조절합니다.",
    instructionsEn:
      "A staff-shared house blend — mix all ingredients well. Adjust the numbing heat with the chili oil and Sichuan pepper oil ratio.",
    sourceUrl: "https://www.facebook.com/HaidilaoKorea/",
    sourceName: "하이디라오 코리아 공식 (매장 터치스크린 메뉴 소스 구성)",
    sourceNameEn: "Haidilao Korea Official (in-store touchscreen menu sauce guide)",
  },
  {
    id: "24",
    slug: "all-purpose-soy-braising-sauce",
    name: "만능 간장 조림 소스",
    nameEn: "All-Purpose Soy Braising Sauce",
    flavor: "짭짤",
    country: "한식",
    spiceLevel: 0,
    celebrityName: "김대석 셰프",
    celebrityNameEn: "Chef Kim Dae-seok",
    likeCount: 168,
    createdAt: "2026-08-14",
    saved: true,
    liked: false,
    ingredients: [
      { name: "대파", nameEn: "Green onion", amount: 50, unit: "g", densityGPerMl: 0.3 },
      { name: "양파", nameEn: "Onion", amount: 100, unit: "g", densityGPerMl: 0.35 },
      { name: "식용유", nameEn: "Cooking oil", amount: 200, unit: "ml" },
      { name: "감말랭이", nameEn: "Dried persimmon", amount: 80, unit: "g", densityGPerMl: 0.6 },
      { name: "생강", nameEn: "Ginger", amount: 10, unit: "g", densityGPerMl: 0.6 },
      { name: "다시마", nameEn: "Kelp", amount: 5, unit: "g", densityGPerMl: 0.3 },
      { name: "진간장", nameEn: "Dark soy sauce", amount: 400, unit: "ml" },
      { name: "물엿", nameEn: "Corn syrup", amount: 400, unit: "g", densityGPerMl: 1.4 },
      { name: "소주", nameEn: "Soju", amount: 100, unit: "ml" },
    ],
    instructions:
      "1) 팬에 식용유를 두르고 썬 대파·양파를 노릇하게 볶아 파기름을 냅니다. 2) 감말랭이를 물과 함께 곱게 갈아둡니다. 3) 물에 생강·다시마·베트남고추를 넣고 10분간 끓여 채수를 냅니다. 4) 채수에 진간장·물엿·간 감말랭이를 넣고 약불에서 15분간 끓입니다. 5) 파기름을 짜서 넣고 5분 더 끓인 뒤 식힙니다. 6) 다 식으면 소주를 넣어 보존력을 높입니다. 김치냉장고 보관 시 최대 6개월, 조림·볶음 요리에 두루 활용할 수 있습니다.",
    instructionsEn:
      "1) Sauté sliced green onion and onion in oil until golden to make scallion-onion oil. 2) Blend dried persimmon with water until smooth. 3) Simmer water with ginger, kelp, and Vietnamese chili for 10 minutes to make a stock. 4) Add dark soy sauce, corn syrup, and the blended persimmon to the stock; simmer on low for 15 minutes. 5) Stir in the scallion-onion oil and simmer 5 more minutes, then cool. 6) Once cool, add soju to help it keep. Refrigerated, it lasts up to 6 months and works in braises and stir-fries.",
    sourceUrl: "https://www.youtube.com/watch?v=2kuWgEuT8To",
    sourceName: "유튜브 · 김대석 셰프TV",
    sourceNameEn: "YouTube · Chef Kim Dae-seok TV",
  },
  {
    id: "25",
    slug: "cold-salad-mixing-sauce",
    name: "냉채 무침 소스",
    nameEn: "Cold Salad Mixing Sauce",
    flavor: "짭짤",
    country: "한식",
    spiceLevel: 0,
    celebrityName: "김풍",
    celebrityNameEn: "Kim Poong",
    likeCount: 58,
    createdAt: "2026-08-15",
    saved: false,
    liked: false,
    ingredients: [
      { name: "다진마늘", nameEn: "Minced garlic", amount: 0.5, unit: "큰술" },
      { name: "맛술", nameEn: "Cooking rice wine", amount: 1, unit: "큰술" },
      { name: "간장", nameEn: "Soy sauce", amount: 1, unit: "큰술" },
      { name: "설탕", nameEn: "Sugar", amount: 10, unit: "g", densityGPerMl: 0.85 },
      { name: "식초", nameEn: "Vinegar", amount: 1, unit: "큰술" },
    ],
    instructions:
      "다진 마늘을 볼에 담고 맛술·간장·설탕·식초를 1:1:1:1 비율로 넣어 골고루 섞습니다. 냉채나 무침 요리에 곁들이면 좋습니다.",
    instructionsEn:
      "Put the minced garlic in a bowl and mix in cooking wine, soy sauce, sugar, and vinegar in a 1:1:1:1 ratio. Great with cold salads or namul-style dishes.",
    sourceUrl: "https://namu.wiki/w/김풍/냉장고를 부탁해 15분 레시피",
    sourceName: "나무위키 - 김풍/냉장고를 부탁해 15분 레시피",
    sourceNameEn: "Namuwiki - Kim Poong's 15-Minute Recipes (Please Take Care of My Refrigerator)",
  },
  {
    id: "26",
    slug: "vinegared-gochujang-pasta-sauce",
    name: "초장 비빔 파스타 소스",
    nameEn: "Vinegared Gochujang Pasta Sauce",
    flavor: "매콤",
    country: "양식",
    spiceLevel: 1,
    celebrityName: "김풍",
    celebrityNameEn: "Kim Poong",
    likeCount: 94,
    createdAt: "2026-08-15",
    saved: false,
    liked: false,
    ingredients: [
      { name: "카펠리니 파스타", nameEn: "Capellini pasta", amount: 100, unit: "g", densityGPerMl: 0.4 },
      { name: "토마토스파게티소스", nameEn: "Tomato spaghetti sauce", amount: 4, unit: "큰술" },
      { name: "초고추장", nameEn: "Vinegared gochujang", amount: 2.5, unit: "큰술" },
      { name: "참기름", nameEn: "Sesame oil", amount: 1, unit: "큰술" },
      { name: "통깨", nameEn: "Sesame seeds", amount: 0.5, unit: "큰술" },
      { name: "깻잎", nameEn: "Perilla leaf", amount: 10, unit: "g", densityGPerMl: 0.2 },
    ],
    instructions:
      "끓는 물에 소금을 넣고 카펠리니 파스타를 4~5분 삶아 찬물에 헹궈 물기를 뺍니다. 볼에 파스타와 참기름·토마토소스·초고추장·통깨를 넣고 골고루 버무린 뒤 채썬 깻잎을 곁들입니다.",
    instructionsEn:
      "Boil capellini in salted water for 4-5 minutes, rinse in cold water, and drain. Toss the pasta with sesame oil, tomato sauce, vinegared gochujang, and sesame seeds, then top with shredded perilla leaf.",
    sourceUrl: "https://www.10000recipe.com/recipe/7074968",
    sourceName: "만개의레시피 - 냉장고를 부탁해 김풍 비빔 파스타 레시피",
    sourceNameEn: "10000recipe.com - Kim Poong's Mix Pasta Recipe (Please Take Care of My Refrigerator)",
  },
];
